---
title: "data_manipulation"
output: github_document
---

```{r setup}
library (tidyverse)
library (dplyr)
```

Load in the FAS liters data 

```{r load data}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```


#select picks columns

```{r select}
select(litters_df, litter_number:gd_of_birth) #selects a range of colomns

select(litters_df, -litter_number) #removes columns
```

renaming with select
```{ r renaming select}
select(litters_df, GRP = group)
```

```{r select helpers}
select(litters_df, starts_with("gd"))

select(litters_df, litter_number, everything ()) #moves litter number to begnning. Also can use relocate.

relocate(litters_df, litter_number)
```

#filter selects rows
```{ r filter}
filter(litters_df, gd0_weight < 22) #use logical operators to slect data

filter(litters_df, gd0_weight >= 22)

filter(litters_df, gd_of_birth == 20) #test for equality

filter(litters_df, !(gd_of_birth == 20)) #not equal to

filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)

filter(litters_df, group == "Con7")

filter(litters_df, group %in% c("Con7", "Mod8"))
```

## mutate

```{r mutate}
mutate(litters_df, 
       wt_gain = gd18_weight - gd0_weight, #creates new variable
       group = str_to_lower(group)) #modifies existing variable
```


## arrange
puts things in order
```{r arrange}
arrange(litters_df, pups_born_alive)
```