---
title: "data import"
output: github_document
---

```{r setup}
library (tidyverse)
library(readxl)
library(haven)
```

## read in data

Read in the litters data set

``` {r read in data}
#load data 
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

```

## take a look at data
Printing in the console

```{r look at data}
litters_df
skimr::skim(litters_df) #gives information about the variables 
```

## options to read_csv
check out ?read_csv for more options/information

```{r read_csv}

litters_df = read_csv("./data/FAS_litters.csv", skip = 10, col_names = FALSE, na = c("", ".", "NA", 999))

```

## other file formats
read in an excel file
```{r read excel}
mlb_df = read_excel("./data/mlb11.xlsx")
mlb_df
# can specificy sheet and range options with excel
```

read in a SAS file
```{r read SAS}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
```

## Comparison with base R

what about read.csv?

```{r read.csv}
litters_base = read.csv("./data/FAS_litters.csv")
litters_base = read_csv("./data/FAS_litters.csv")

## want to only use read_csv!
```

## Exporting data

```{r write csv}
write_csv(mlb_df, "./data/mlb_subtable.csv")
```
